### PR TITLE
a starter bedrock json file

### PR DESCRIPTION
**Pull request by roblatham00**

### CODE REVIEW

**Comment by mdorier** [comment]
@roblatham00 Could you edit this file: https://github.com/mochi-hpc/margo-microservice-template/blob/main/.github/initial-setup.py
- Lines 96 and 102 add `'.json'` to the arrays of extensions
- Lines 98 and 105 add`'initial-setup.json'` to the arrays of files to exclude
That way the github action that looks for "alpha" and replaces it with the actual service name will also process your example file.
Thanks!

**Comment by roblatham00** [comment]
good catch.  updated!

**Comment by roblatham00** [comment]
oh, whoops I tried making a project from that template and the alpha-provider.json file does not show up ... https://github.com/roblatham00/jsontest

**Comment by roblatham00** [comment]
maybe its weird using a branch for the template?  i'll try again

**Comment by roblatham00** [comment]
yes, that must have been it.  alpha-provider.json is renamed and visible in new project.  ok, carry on!

**Pull request merged**
